using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DoubTech.AI.ThirdParty.ElevenLabs.Streaming.Data;
using Doubtech.ElevenLabs.Streaming;
using Doubtech.ElevenLabs.Streaming.Data;
using Doubtech.ElevenLabs.Streaming.Interfaces;
using DoubTech.Elevenlabs.Streaming.NativeWebSocket;
using DoubTech.ElevenLabs.Streaming.Threading;
using Meta.WitAi.Attributes;
using Newtonsoft.Json;
using UnityEditor;
using UnityEngine;

namespace DoubTech.ElevenLabs.Streaming
{
    /// <summary>
    /// Handles the WebSocket connection to Eleven Labs, sending and receiving streamed audio messages.
    /// </summary>
    public class ElevenLabsWebsocketStreamer : BaseAsyncMonoBehaviour
    {
        [Header("Eleven Labs")]
        [Tooltip("Configuration settings for Eleven Labs API.")]
        [SerializeField] private ElevenLabsConfig config;

        [Header("Audio Player")] [Tooltip("Audio player used for outputting audio")]
        #if VOICESDK
        [ObjectType(typeof(IStreamedAudioPlayer))]
        #endif
        [SerializeField] private MonoBehaviour streamedAudioPlayer;

        [Header("Debugging")]
        [Tooltip("If true, debug files will be written when audio is received from the server.")]
        [SerializeField] private bool writeDebugFile;

        private WebSocket ws;
        private Queue<AudioRequest> messageQueue = new();
        private Queue<AudioRequest> activeRequests = new();
        private TaskCompletionSource<bool> _connected;
        private FileStream debugStream;
        private FileStream responseStream;

        private bool isProcessingQueue = false;
        private bool _initialMessageSent;

        private IStreamedAudioPlayer audioPlayer;
        private TaskCompletionSource<bool> _messageQueueTask;

        private float timeout = .25f;
        private Coroutine enforcedTimeCoroutine;

        private bool IsConnected => ws?.State == WebSocketState.Open;

        private void OnValidate()
        {
            if (!streamedAudioPlayer) streamedAudioPlayer = GetComponentInChildren<IStreamedAudioPlayer>() as MonoBehaviour;
        }

        protected override void Awake()
        {
            base.Awake();
            if (streamedAudioPlayer) audioPlayer = streamedAudioPlayer.GetComponent<IStreamedAudioPlayer>();
            else audioPlayer = GetComponent<IStreamedAudioPlayer>();
        }

        private async void Update()
        {
            ws?.DispatchMessageQueue();
        }

        private async void OnDestroy()
        {
            if (ws != null)
            {
                await ws.Close();
            }
        }

        /// <summary>
        /// Initiates a WebSocket connection.
        /// </summary>
        public void Connect()
        {
            ConnectToWebSocket();
        }

        /// <summary>
        /// Sends a message to be spoken by the Eleven Labs API.
        /// </summary>
        /// <param name="message">The message to be spoken.</param>
        public void Speak(string message)
        {
            audioPlayer.Stop();
            messageQueue.Clear();
            Enqueue(message);
            _ = ProcessMessageQueueAsync();
        }

        /// <summary>
        /// Sends a message to be spoken by the Eleven Labs API.
        /// </summary>
        /// <param name="message">The message to be spoken.</param>
        public async Task SpeakAsync(string message)
        {
            audioPlayer.Stop();
            messageQueue.Clear();
            var request = await SpeakQueuedAsync(message);
            await request.Task;
        }

        /// <summary>
        /// Queues a message to be spoken by the Eleven Labs API.
        /// </summary>
        /// <param name="message">The message to be queued and spoken.</param>
        public void SpeakQueued(string message)
        {
            Enqueue(message);
            _ = SpeakQueuedAsync(message);
        }

        /// <summary>
        /// Queues a message to be spoken by the Eleven Labs API.
        /// </summary>
        /// <param name="message">The message to be queued and spoken.</param>
        public async Task<AudioRequest> SpeakQueuedAsync(string message)
        {
            var request = Enqueue(message);
            await ProcessMessageQueueAsync();
            await request.Task;
            return request;
        }

        private AudioRequest Enqueue(string message)
        {
            var request = new AudioRequest()
            {
                message = message,
                charsRemaining = message.Length
            };
            request.onComplete += HandleComplete; 
            messageQueue.Enqueue(request);
            return request;
        }

        /// <summary>
        /// Stops the audio playback and clears the message queue.
        /// </summary>
        public void StopPlayback()
        {
            messageQueue.Clear();
            audioPlayer.Stop();
        }

        /// <summary>
        /// Pauses the audio playback.
        /// </summary>
        public void PausePlayback()
        {
            audioPlayer.Pause();
        }

        /// <summary>
        /// Sends a test message to the Eleven Labs API for playback.
        /// </summary>
        internal void PlayTestMessage()
        {
            var file = Path.Combine(Application.dataPath, "test.pcm");
            if (writeDebugFile) debugStream = new FileStream(file, FileMode.Create);

            ProcessMessage(
                "{\"audio\":\"AAACAAIAAQD///7//v/+//7//v///wAAAAAAAP//////////AAAAAAIAAgABAAIAAgABAAIAAgACAAIAAQABAAEAAAABAAEAAAABAAEAAQABAAEAAQABAAEAAAAAAAEAAQABAAEAAQABAAEAAQACAAEAAQABAAAAAAABAAEAAQABAAEAAgACAAIAAQABAAEAAgACAAIAAgACAAEAAQABAAEAAgACAAEAAQABAAEAAgABAAEAAQABAAIAAQABAAEAAQABAAEAAQABAAIAAgABAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAEAAQABAAEAAQACAAIAAQABAAEAAgACAAEAAQABAAEAAQACAAIAAQABAAEAAQABAAIAAgABAAIAAgACAAEAAQABAAEAAQACAAEAAQACAAIAAQABAAEAAQABAAIAAgACAAIAAgACAAIAAQABAAEAAgACAAEAAgACAAIAAgACAAIAAgACAAIAAgACAAMAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAwACAAIAAwACAAIAAgADAAIAAgADAAMAAwADAAMAAwADAAMAAwADAAIAAwADAAMAAwADAAMABAADAAMABAAEAAQAAwADAAQAAwACAAMAAwADAAMAAwADAAQABAADAAIAAwAEAAQABAAEAAMAAwADAAMABQAFAAUABQAEAAQABAADAAMAAwAEAAQAAwACAAMAAwADAAMAAwADAAMAAgADAAMAAgADAAMAAwADAAMAAwADAAMABAAEAAMAAwADAAQAAwADAAQAAwACAAMAAwADAAQABAADAAMAAgABAAIAAgACAAEAAQABAAEAAAABAAAA//8AAAAAAAD///3//v/+//3//v/+/////v/+//3//f/+//7//v/+//7////+//3///8AAP///v/9//3//v/+//7//v/+/////v///////v8AAAAA//8AAAAA//8AAAAAAAABAAEA//8AAAMAAwADAAMAAgACAAIAAQACAAIAAwADAAQABAADAAQAAwAEAAUABgAGAAYABQAFAAYABwAIAAgACAAIAAkACgAKAAkACgALAAoADAALAAkACwALAAsADAAKAAkACgAKAAoACQAIAAgACQAIAAgACAAJAAgABwAHAAUABQAHAAcABgAGAAQAAwABAAAAAgADAAIAAgAAAP3//P/7//r/+f/5//j/+f/6//r/+v/5//j/+P/4//b/9f/0//X/9f/0//T/9f/0//T/9f/0//X/9v/1//X/9f/2//b/9f/2//f/+f/6//j/9//5//j/+f/7//r/+f/4//j/+v/6//v///////7/AAD///3/AAD9//z/AQACAAMAAgACAAQABAABAAIAAgADAAIAAgAGAAUABQAEAAMABQAGAAgACQAJAAoACwANAA4ADgAPABEAEQASABQAFQAYAB0AHQAaABcAFQAVABUAFgAXABUAFQAWABUAFQAVABMAEgARABAADwANAA4ADgANAA0ACwAKAAsACQAHAAUABAADAAQAAQD+/wAAAQD///z/+P/4//f/9f/1//b/9v/0//L/8//1//H/7P/s/+//8f/t/+n/6v/r/+r/6v/r/+3/6//p/+r/6//q/+v/6//s/+7/7P/p/+f/6P/v/+//7f/s/+v/8P/x//D/8//y//T/+P/3//f/+f/7//z//f/7//r//f8AAAIAAwABAAMABgAIAAcABwAKAA0AEAAQAA4AEgAXABYAFwAYABgAGwAcAB0AHgAfACIAIwAhACIAIQAjACUAIAAgACMAIQAhACMAJAAjAB4AIAAiAB4AGwAdACAAHQAYABUAFwAUAA4AEAAPAAoACAAHAAUAAgD//wEAAgD8//n/+f/4//b/9P/0//L/8P/w//H/7f/q/+n/5//k/+H/5v/k/97/4f/g/9v/2P/W/9j/1//W/9f/2f/Y/9b/2v/d/9r/2f/a/9n/1//Y/9n/2v/d/9//3f/d/+D/4v/j/+T/5f/p/+3/7f/v//L/8//1//r//f/8//z/AAAEAAMABAAJAA8AEAAPABIAEwAVABcAFgAZAB0AIAAjACEAIwApACwAMAA0ADcAPQBBAEQASQBMAE4AUABMAEsAVABcAF8AWwBdAGUAaQBqAG4AeQCEAIEAfwCEAIwAkQCPAI4AjQCIAIMAegBwAGkAXwBbAFoAVgBSAEwASgBFAD0ANAAlABcAEAANAAoACAADAPX/4v/O/73/s/+m/5f/jv+F/3v/ef+B/4j/hv+D/3//a/9d/2b/av9e/1j/kf/d/6H/Mf8o/1H/YP8x/xP/Qf9l/1z/Xf91/33/ef98/3X/Y/9d/2b/df9//4P/jP+L/33/eP94/3L/dP+F/5v/q/+z/8j/5f/w/+j/4//s//X/+f8BAA8AIAAqACwAKQApACoAKgAuAC4AMQA/AEkATABXAGIAZgBmAFwAUABNAEwAUgBZAFMATQBWAFwASwA0AC0ANAAyAC0AMgA0ADQAMQAyADcAMQAmACAAHQAcAB4AHgAdABsAGQAaABoAFgAXABsAGwAhACkAMAA3AD4ASwBOAEcATgBaAFkATgBHAEsAVABZAFQAUgBdAGEAYQBdAFgAXABjAGYAaABmAGQAaQBsAGoAZABeAFoAVABOAEgASABIAEUAPwA1ADMANgA0ACwAKAAoACgAJgAkACUAHgAQAAkABwAEAPj/7P/r/+r/5//k/9//2P/T/87/yv/J/8n/x//B/73/wf/D/7r/tP+1/7P/rf+l/6H/pP+n/6n/rP+v/7H/rP+k/6X/qf+t/7H/s/+1/7b/uf+9/77/vf+8/8H/yP/N/83/zv/S/9b/2v/a/9j/2v/c/93/5f/o/+X/5P/n/+7/8f/w//D/8//2//T/9v///wcABQAEAAMA/f/+/wQACQAJAAAAAAACAAIACwARAAwACAACAAAABAAJAAwADgASABEACQAJAA4ADgAOAA0ACAAGAAgACwAQAA0ABgAFAAkABQAAAAQABwAFAAQABgAGAAUAAQD7//7/BAAFAAUA///7/wEABgACAAAA///+/wEAAgD9//7/AQD8//3/CQAIAAAABAAFAAIA/v/6/wEABwADAP///f/4//T/9/8AAAUA///8////AAAAAP///f///wMAAwD///3/AwAHAAMA/v/7/wEACAAFAAQACAAJAAYACAALAAwACQAGAAoAEAAQABAADgAQABIAEAAMAA8AEQAMAAoAEAAUABMAFAAXABQAEAAOAA8ADAAKABEAEgAPABIAEQAQAA4ADAANAA0ACwAMAA8AEAANAAsACwAOAA8ADAALAAwACwAHAAEAAQAFAAkACQAIAAUAAQABAAYABgAEAAQAAQD///////8DAAIA+v/6/wEABgABAP3//f/9//v/+f/6//v/+//5//j/+f/5//v/+//4//f/+f/8//j/9v/4//j/9f/y//P/9f/0//f/9v/w//D/9f/3//X/9f/2//j/9v/y//T/9v/0//X/9//1//X/9v/2//j/+P/2//f/9//2//f/9v/1//b/+P/3//r//P/4//f/+//8//r/+P/1//T/9v/6//v/+f/4//f/9P/1//b/9f/3//X/8//3//X/8f/0//b/9f/2//b/9P/2//j/9//2//L/8P/0//j/9v/0//T/8//0//b/9//1//X/9//4//b/9f/2//b/9//4//j/9//4//r/+P/3//n//P/8//z/+v/6//z//f/+/////v///wEAAQAAAAIAAwACAAIAAwAFAAUAAgADAAcACgAIAAUABgAJAAoACwAKAAoACgALAAoACQAKAAwADAAJAAcACQAKAAoADAALAAoACQAJAAkACQAKAAoACgALAAoACAAIAAQABAAIAAcABwALAAsACgAGAAMACAALAAgACAALAAoACAAHAAYABQAIAAkACAAIAAcABgAIAAgACQAJAAQAAQAFAAsACgAGAAMABAAKAA4ADAAJAAgABwAEAAQABwAJAAcABgAGAAEA+v/9/wMAAQACAAkAEAAOAAQA/P8CAAcA/f///xQAHQAPAPb/6P/6/wgA/f8BAAoA+v/2//f/6f/t//X/+v8SAAYA0//Q/wAAKAArAPP/wP/c/xEACgDY/8r/1v/Z/+z/EwArAD8AQAD4/7//6/8hAPH/mf+3/y0AQQDj/6X/qP8NALIApQDl/zn/Ev/A/9UAPAGpAHz/iv7Y/gAA0ADBAAMAw/+PABMBjACP/9D+GP/z/yMA5//k/9n/tP/U//b/yv/+/5MAmABfAHkA6//A/oX+Zv9qACgBaAGuAFT/dP7y/oIAmwEVAZf/v/4G/7L/ZwChAcIBdP/e/Sn/eAFyAk8BQ/+C/jv/nv+Z/ykAfgDt/27/zP/cAYUGYAxgDjUGm/VI6GzlBOyG/MoRrhnUCUXzle6k/HANfhNQCKH2ZPNj/VQE+AJ8/wEI/BRrCRPwU+2p/lMLygru/rbyBPbv/mH8mf50Df8QBgceBg4FefLo6qD82QjsBRcCOf1o+Z/8JAFrCL0K4ftA8m/5Sfmk73bxyPt+/qr+eAOLBZgHEgrU/5L16/2iBwcGwAMUAGv3UfedAScIPgcbAjH8ivucApgFkQAn/aD48fMx9fr7TAhlFDQWuwca9MT0ogheE1EPVwfX+cztN+8D+moJTRIzCZ/9ZfzX+zH1IfXlB04VbQD95WvvFgK4ABEGjxFKBmfzIe+q9HwAuQbUBIMJlQMI737tgfz/AxwHYA1LDtb+1ezN82cJeRF2C2v9e+538BsGoxc2EiIAafiN/wMDA/7Y/FAB8Qa0Bj/8yu/q7ab+xRlDIGwBrtza20T8cRm+FXj4xedp8NL9AwgLEbgK6vaZ8Yn5hvoM+3IBhgHgAVAJygZ5/qb/eARsCPsIe/zM71T4BwbKB4QHQweXAZL+fAUzCkMEYgBmBdcK1QjSALr9jAAO/3/5rvjx/UAF6QpmBmr6VvMh9Ib9cwrZDPT97enT5TH4cw0gDYX9zffs/cAAmQB3/8H4j/SY9xP+twSjAzH9Ofge8c/wRwBEDT0KwP0N9HX3SgErBOsDQwUdAPv3bvgT/zUFfAcAAz36nPVe+wcHIQwnBjr9afxUAFL8pPON9R0FeREnDXX8E+3D7ckDRRzKFuj48uad6mv8zhJ/GPUJb/tV9AH1/ABuDEgMmQfXAsT60fIs87f6p/8ZAyMK5QzyBKX6B/oMAZcFDQTXAMb+e/qp9S/3P//1BlcKDAo4BSr+V/3QA2wHAwLV+fL1GvV6+lgIZA9rCG8DwgZ7Bt3/6vs3/kwEEwev/hf06fZo/04BGARcCVAIQQRfA7oEuwaaBDv94Pc09UX07vr8BwYQwwsLAbz7C/9BBCQH/AU+/Rv0LvZ++536ffy4AikE6QF9/xn+ygFgBgQFJAL4/ln4EPTJ9Db22fiJAGwL/RCnDHEDvvuK+LL6s/3U/eH9LwBFAhb/3fgl+SYCjwy5DygIlPyL90778wGxBnwGhP9197f0sPhbAikLGg1uCRMBofSJ7ErucfW6/sgFPASO+y/1sva+/RoFMAdAA839xPrZ+UP7E/9OAJ38zfgt+s7/8wbjDpwRcgkR/lf5GPpc/Bf+j/yr+S36mP62Bm8Ouw4lCeMEvQM1AYv8NviX9dn1BPi3+vH8IgCPBg8OSxHOC5QAc/g79vr0fPQU+L79XQAL/TX6CACfCBkKWQhLBlMAc/vf+QP4ZPd0+Kb5tPzxAeoF9wegCocL3ghfBTj+i/bY+K4A8AMBBIEBBPzn+pT/YwbCCzYK7QMy/sL6jPp4/RcBXgFs/PD3RfugAnEJZg+yDQ==\",\"isFinal\":null,\"normalizedAlignment\":{\"chars\":[\" \",\"T\",\"e\",\"s\",\"t\",\" \"],\"charStartTimesMs\":[0,35,116,232,313,430],\"charDurationsMs\":[35,81,116,81,117,174]},\"alignment\":{\"chars\":[\"T\",\"e\",\"s\",\"t\",\" \"],\"charStartTimesMs\":[0,116,232,313,430],\"charDurationsMs\":[116,116,81,117,174]}}");
            ProcessMessage(
                "{\"audio\":\"EgM1+kL39Pb5+vsCzwYJAgr63fXa+IQBQwrYDPUHqwAQ+675FPyP/a79ef53/7oB3ga0DCUPJwxaBFz7Avds+Qj/pQP+BEQD6ABR/+j+tQABAysDdwKTAXf/C/2Y+rL4Afl1+gX79vt1AKwHPwynCeABOfvb90r2M/Zo+BT9wgLvBdcFsgZoCF0G0QBw+z742PjN/IX/I/+x/qn/UgHHAugCIQICAowCWwP1A5ABOvyH+Rz7kPy/+3n6uvsqAYEH3ghqBLT+/vqq+WP58Pjp+PX5UPwM/6QAkwGZAh4DDgO8AkkBqP6Q/Q4AUgMOAjj8aflf/TsCgQNnAooBKQKkA94D4AHN/6n+C/3G+q/6Yf3r/2MB8AEcAksChQAi/Yz8qP7V/uf9gf6n/hH+Yf6q/g7/XwBzAakB6gAy/479j/z0+2T8Cf5q/48AnwJ3BRMICAlaCLgGoAOB//r8wPy9/MP93QAXA7EDmgSQBA4DywIeAz4C6QDs/s382Pty+7n7+/2aAD0BAAGKATgDdQX9BZ0CI/2P+Q/4Rvdb+Pn78P90AuMDmwQiBawFswT3ATH/BP05+2f6LPsr/bP/tAGzAosDewTlBCoErQKDAWgAg/51/KX7Wfwn/n8AlAIrBBcFDQVOBL8CCQBh/cH7wfq4+qH7r/za/YD/ZwG/Au4C6wGSAGv/K/7z/Ab8ifvo+6H9/v+zAbYCegMcBBoELgPdAboA/v9X/4/+sP1E/QX+8/8aAoYDDQRPA44B6v+5/uv9z/0l/kj+lv4p/zf/8/4A/3b//v/G/5j+kf2z/bj+2/+gALMA7P/l/n3+wP47/6X/BgBKAFwAeACZAL4A/QDaACIAmP/J/3kAIQEjAYwAdQBkAZMCfAMoBGgEQwQGBFYDSQLHAbIBjgF4ATQBbwCi/xn/7P52/+//c/+Y/sH9ePxU+1H7GPwq/fT9kP2L/Cr8mPzA/XH/3gCjAeoBRQFX/0v9T/xT/OX8mv1I/nX/0gG7BJsGqAYUBeACNQFKAOz/NQDKAA8BfQF5AgsDnAJpArkDZwXMBa4EfgLAABwAO/+s/WX8tvuG+4n83f5VAZsC2AEX/wX8bfqB+s/7CP1Q/Ur9hP3e/Zz+cQALAukBNwGTAOX+Fv0w/XT+lP/KAJcBKwKjA8IEjQQFBEMDCALuALL/2/3B/Gb9Mv+WASAEFQZyBtwEYwI9AKr+Lf2D++35wvjk+Kr6L/3x/8ACVgQbBLkDLQNCAeX+fvwV+mH5vPpL/Jb+lwKsBjoJ9wg/BqwCYf70+YL3Gvf99pn36fmn/dcBWgXEB0YIygafBGUBkPxe+B/3L/jT+Uv7RfzD/fYAdQVTCokNdQ39CgEHZwE9/EL62fpb/IT+8gBlAy0GpwmZDeQPZA5DCTQCpvsV9wH1J/eF/YwD+AX0BRcEPAFfAOkARQAH/4z9Lfsd+TT45Pdv+Kf5qfrE+1H95v54AGwCkAODApz/hvs3+CL4N/sIABYG1Au6Di0O2QqtBrYDsgEKAPD+Z/6w/n4AXwPaBWoHFAccBIcAW/2n+mv5/viI+Hr4Zvh093D2lfZa99v3Avjb9/L3BPmU+kf7x/qk+Tz4EfeD9q728PeD+ln9oP5k/q/9yvyA/IH9Qf+cAfgDfAQaA1sAzvxA+sD5aPuE/hABXQHD/3b9fvtH+9X8OP6T/k3+e/2s/Mv8yv1d/zYBawJ1AlICkgM+Bp0J1gzCDlQPMQ9yDhIN4Qu2C64MSA7OD2EQyBAbEisRoAyhB64EiQS7BpAK3w0JDx8OwgoeBl8CJgD3/g3+Of1I/PH6Z/ka93X0R/IZ8Cfux+1R8dT4ygFKCkwQ7BJvEgAObAZSAA0ATATAB3AH4QMF/3n7jvv5/n8DSQf8BBv6gu5l6MbqIfau/2T/8/cW64ne1N0X7nsMEC5sQ7NGUTrMIfsDDOawyp+1eKiwpdOuScOw4xsJ4yaaNUU0XSZ3D6D2muYO4JnepeNC7OX0CACQC4kWpSNtLno0aTi0NmUs8BuWBwbyBd/50yzVG+AL8QgFQhVOHN0XMghF8VbX4r4BrLGfxpmEndOsoMGC1kDpJPVy+OT1qfDf7KXrkOtl7UrxifZQ/QQGwBGvIqg4X06TXjBog2viZuJXkkDwJhURswOn/koAPQlSF9olRy+eLZgesASC5mDMd7totLG1eLvvwX7KstaH41DtuPBC62HenM/8x5PN7dvN6nL1l/yiBvcYTDKsSxVeqWaOZRJc4Ez7Oycu7CW4IAYc/Bc4E+0MhwYvAEf5NfIB6x/jHNs307XL/caHxiTJzMzBz+jRo9P51A7Ykt1O5BTuBPnLAM0Hyg+kF/YfTyZnJ/MjtB0hFmIPjA0KEfYTPhSaFIMVIhhDHtklZS3JNOc5OT6rR/ZVKmCRV6EwA/XYu6SVfoYHhtORe7JD5vsgC1AgYH5SWzdZF73zlNEHudiv37pp3jsUsUeKZ3tzvXQRcFxmW1vATLs1Qhpx+43WprI2nIKZ1akRySvsdQQXC3z/Que7zlu88KyznMmOMYgLiHONXZv2s1LTq+9OAfgGcAWRAwIE8gTSBM8FwQzUG8UvgUQSVndhOGhobPNu2HB9cjlxzWcAU5gunv5V1h7DkcZH3Uf8gBRHG5EOYvOq0zG6H6s9oomaxJP1j9+QwJeppLq0OcNJztbWst2I5TfzkggDIk83zT7WNs8pHyW3LnRCbFj1acJy3nIVbRhkyFgCS0Q6hCauEZ79qe4V6jru+PTZ9tXttNvSxSaxcKLzmZyVOZSLlCOW1Jl+oMqrEbykznHh/fAe+hj+FP5w+zb73wCsDNweATSnRzhYp2O0aM5oNmWbXIhPakDuLdcZ6AoYAsH74PWc8KnuSPEh9RP3tvcF+ugAdA5WIhI21zzKKtwAt8yfoB+KwIXujIumdtQUDodFkWY0arhYxDmWEvTohMf6thm7PNi5COg5UF3jb6F1GnRQbU5iqVM1P8IlEwpF6/DKDbLYqZmzMspn5qv99gVK/YDpQ9M4wHKwXqH5kpSJaoeqi8+bz75z7UkWpS5WNT0tXhyMCNv4ZPV0/SYMTyAfN/RKKljeX2llJ2qBbWlvj2+2agxdfkPMHk/41tdAwb+6nsY34pICShcjGrkLYu69y2qv4p12lfSSYZRfmdKj4LTKyDXc4+2b+Rr8q/k/+5AH+BvwLpQ6OD0WOQA1BjjbRMVWNWUGa1xohF77TkQ8zCZUD2j4bOTU1SLOYs3uz/7QPc7CxrG766/ZpnuhCJ9qn66h8qUUrv66K8xU3xvyYQIbD4oZrCBqJGgmPyZ3JX0mFylYLEQxxjcjPhpClUP9QbM6bzB9IvkRIAMw9O7mpN3N2NzaDeN25k/grdlN12/YqNyT6WcCRh7ZMO4yACVuA1/OxJ7diZCMTqr05OQkz1Q0bwB2eG/EW1s86hkC96jZotCN4i0Lvjp+XllxJ3ercplki07jNJkegw5H/jzor805s5ehuqHBshnLGN9S58fiVNQEwwG1YapPoJSV4Yw0iQCLP5TIqsPRlgAMJ7E6xzujMBsgERFrCQgK3RHjIFk04kcKWJ5iIWiiaohreWvNakVoQ2DNTT8t7wIY29O/vLVsvcnPGeHn6ZTnodtTy/W7k68vpN+YjZEvklGbw6y6w0jZ9+li9VD79/9uCcka6DBaRRFUellxUw1FIDdJMlo49kYtWa9oWXHhb/FhWUgnJ/4Epuhy1DrH48Bxv9q+7r0hvMy347D1qPKhYZ0Im3aZ3pjAmhuhZ64BwhPZsvCzBdUV9B+ZJBQlsiP0ImMjhiVkKfktYTMoOiJCB0oWT/tOf0enOJQlvRE5AZf1Vu2i5Z3eotvk21Td0tyA1pLPE83rzKnQ3NvJ7zAIfh/KMU44MS7lCqjQ9Z4DizmQfLSv9vI3DWIMddp3lG2+U40vwAd24ZPL4s+e7W0dx0rRZsFzQHVwaypY5z76JH4RVgMm8qvanL85p5KaaZ8Fs0HMW+Fc7YfuiePxz7u7xqrOm7ePKomZiBqPBaGHxEr3TyiBRntM+T46Jh0L8Pjz9cf/AxJGJy86cEn8VVxfNWbWaxxvC275ZktZvUTIKAgIv+fPzee/oL/nyRbZ9Oey8uv0Pu0R3uXKx7YWpOSXMJYSnzOxssjB31LyDP/UBTYJtg2NF9ImFTU4PVs+uDm5M/gwdTRNP5ROPF0VZwVqGmTXUiY32BSE81ncGdI20m7XdNyV3R3YMM5qwwy5tbApq/Wn86XKo8ChHaG+pOevKMO22uDwvAOqEmccWSEfIuYf3BxyG2sdhiI6Kv8ygjqVQKZDSEHcOmcyQSgIHcwQ6gOH+WfzTO/e6ijll9481/nOAckvyD/LBs/Y0P7QCtUM4ZLzKg0dLLJIVFguT/0nfOrwsEWUP5YPtkfwuS0+WV1wb3cycVRf8UKkHKbxEs1guSm9UdnPBtA2TVuqbn5xd2bsULY2AB1hBhTzO98VyJuwLKG+oZKyeM3e6M76EwCp+23wSODbzRS84Klul2OLlolhld2zueHAE7Y8fVNIVnhHli5kFiMGGwCfAjkLQRpUL1dFiVaTYUxoCGzXbHto+1t8Rt4nrAUp6CHQIL+eurrDJtnl9c4OIBmcDrnxFs4xr6CbE5U6mEegH6rEteDFxtsv9UsN5x5nJlkkEB5HGs4cfSOEKJsnCiHTGQkZ0yNhOXhSc2W/a9diF0ymLS0O+PJ/3+TTzc7PzdrO2tCw0u3TANTV0TfNIMctwAe57LJ/rgitpbAnumjJIN288iMI5xqXKJ0vyC/IKrMi8BojFxAZDiAXKeIwcTWxNms1zTHRK4wkAhyzEZUG5/rk8M3qb+gE6Rvp7eX630DZD9Xf01LUyddQ3NneIuCe39XeK+H+5cTrdPNRAK0VaDKoTmtfTlqlOrsHetNQs7W0ztT5BUg4RV2dbiZuG120P68fGQLb6D3YAdOb2ufuzQq/Jec3Zz3pNgop7RmzDQEFd/0/8wrjyc3nuUavk7KtwvPZwPFTBA8NigmD+wXnc8/Vt12juJW2kgmdKrW51yj9mByxLxU1vS/wI78WRQ0MCR8JRgwdEcYX3SAYLA05y0agUwpdWGDTW1lOVDirHLn/Eee91n/PPdGl2gDp7fg+BZwI8QC478rYWcGSrqWk+aT8rQ29c89B40r3HAlSFb0asxrzFxsVnxPRE5oUzxQgFOMTmBb2Hi8u4kD5UNFYBlRVQiIo4wp+8IXdYtN50UjV7dwC5zvxMPmx+4T2mOmX15zF2LfssEuyf7p/xtnTcOCL63T2eQJzD4McZSfpK2InvBoPC0z/oPzKBPQUYyiJOpBGiEmjQ7w2jCWLEtb/MPDM5a7hB+OH5zTtVvIB9Vf0XvHQ7CjoZuVq5J7kiOVS5vnl0+Ri5MTl2+li8LT3s/6zBD0IiwhwBgUEIAK/AB0B/wKvBlUMYhJJGUUisy7tPhlQeV2gXehGOxrU4Q2w8JUMlqiu/tprDG81Yk18Ttw79h9XA07qodYcyWbEusuB3777vhksM9lCbke8Q3A7ezJUKhggUhBU+tTgP8rovoTDQtau8OwJlhrWHtwVVQNP7LPTXLzIp9SXCpGOlqOpIMjh6s4J0x31I7QfkxZpDTAIiQZyBRAEnwLsAuIHjhIsI+M3QkwfXPRjM2G4UvQ5Axz5/vznSdqm1kDcwOjH+GEI8hIFFdENk/6u6vfW6cYSvI22KrUKtxm9HslK21jxDwfzF54hyyOaH78XSg8MCI4D/wLnBvAPoh1CLuk+bEt8UIxMKkBPLsQaiAhV+U/uFujM5Uvm2+hK7BjvEfCc7rvq0+R93TLVeMzkxHbAb8Dqxa3QoN6d7Tf79ASGCuAMoAztCgEJ5wegCNMLTRF0F+Ic+CB4IwklJCZ+JoglVyIqHEcT7QhF/4H4fvWq9b32rfa09K7wIezL6JXnouhe60fvXfOk9nT4dfhT9+71kPSc813zEPRk9rf6PQHxCdETJx2cI5gkCiCsGGcR1QykC3MMYw50EQEVnxc4GfEZnxiwFNIMtv9d8ZbmIuD73hrjsOpZ9er/TgTbAHr4L/By7efzhwTUG4AxmjqxL0gSduu8xwmzKrTyycDstw8sJ8ovJysAHrwPxwNv+VDxguqg5C/k9Orz9ngFZBEvFxsYnRe8GJ8c0CDGHwgVQAFq6j7YvNBd1R7jYvXLBjMSsBWTEusKWAC/8pvhNs9PwKm4T7lBwarNZdtE6IPypfm6/i0C7AOxBFEFvgb7CLAK3go7Cm4KqA08FgEkDDSEQZhHRkSvODMoVRf/CRMCOgDbAqMG4glOCwcLGwuiCmEHNAEM+Qvx0Ool5s3hnt0n29Ta+txt4nTqAPTP/YEFVQkmCdYFqwBC+1n3qPW+9rv7jgTVD8YbOSZeLZUwKDAILHAkuRoXEFwGdf/J+xL7dfyL/vn/1P9A/lv8AftW+tv5bvgb9arvM+hS39LXZ9TU1ZLc8eb18nv/FQnLDMMK5ATW/UD40vRI8xT0D/eT+80A9wXkCmkPvxLNEyUSZA4OChgG8QFn/cP4m/Tg8kv0F/ix/VgDrwelCqULGwpFBr8Acvq09HDw9e3M7WLw+vRV+rL/SASXB/gJiAsSDKgLygmWBd3/FfvC+Dn5m/yZAc4G1guNDxMREhE6EIUOtgunB+cBK/pC84nvL++186L72wMICxUPwA7hC+sIEQWE/5D6CPfE85ryLfR+9h77/gBSBKwFgAVlA18BvgJ7B70KiwmuAt32NO1O6TrpVe6d9+3/dQSiBAQC//88AIQA4P3K+fj2Ifbu+Pz+HgXWCMAHHAG1977vausW68fuJfXX+yABfQRfBrgHrQi4BwsEH//B+tH3dfaK9sj3vPoiANMGzAwSEJ8PzwsxBi0B1f2v/LP9rP+6AcoCXwLOAcECBwVDB5IIcwgVBzMF0wI8/1n61PSH7wfszOs679L1F/7rBdUKuAuyCDUCUvun9mX0bvWy+Yz/KAZ6DFEQ0hDNDlELxwe9BRsGWghqCwUO8w78DbgLKwnpBtYFWwaOB1MJhAsfDTcNPguPB+ACVv6N+3D6PvoB+3H8U/6NAHQC1wNOBUQGsgURA7z+Ivr29bryQ/Eg8mn0DvcE+rf8K/9PAaQC6wLxAUQAyf2S+qD3V/UH9CT0hvZV+2UBiAfQCwMNGws/BsD/I/nL88vwk/DS8nP28voLAEEFpAkBDLYLkwj3AlL81fYX9Av1c/hR+2D8gPwR/T7+YACrA+8GzQjWBw4EHP+H+lz31vXu9QX4sft5/3gCuwQMBn8GYwadBQIEaQHu/mf8jvmM+H/5ePw5AYkEAwahB34JWQuVDAIMogm0Bfb/Lvmx8wTyMvXO+8MClAj7DKkOHg0ZCeMDP/+3+wX5fPc09+f3WflD+7X9MgEbBcwHOAgrBswCVv+u/E77tvpi+qb5zvhy+Lb4dfqO/ZcAxgIHBFMEsAMAAm7/hPyI+RT30fUd9mn4HPyh/xYCdQPqA4oDkQIwAQH/IvwE+SH2dfWL9zX6wPxr/00BBgP3BSkJIgs1C10IOQNb/tH6t/hW+GD5Zfvp/ZQAOAOQBUUHhwfIBWYC4f1O+XP2wvWI9uD4Svyp//gCgQX7BtoHaQesBdQCF///+236Mfou+3P8Yf1F/ycC8wRkB1wImQcaBvQDJwFn/rj8afwU/av+qgBhAkcEUwabB9EHygabBO4Bl/8F/l793/0A/+v/iwBYAaICUgRsBhkIcwjQB/IFUwP8AKD+m/yu+wP8bP2V/wkCYARiBgQH5gXlA4gBO/9w/Ur84PuB/M/96v60/5YAvgGFAmUC5AEyATYAd/8k/6/+6v3m/MP7X/sz/NX9o/9GAcMCygMvBLEDewLRAYkB5wBoAN//TP98/xkAHQDB/8T/qf/t/s79jvz7+4j8Qf1w/Tn9yPx0/Gn8Wfwe/Ov7E/yl/GH95P2+/Tj9jv0J/7D/6/7b/Uf8BftC+2P8wf32/nT/PP8Y/2L/SwB+ARQCeAL0AvQCSwJhAUEBxgHDARMBEgBG/+P/BAIzBIYFbAUfBCkD6gKSArABhACx/xX/3P6e//UA1gL3BOEFNQXiA7YC9gFeAacAtf/M/lj+Gf5R/mj/xwDwAakC7QLQAlAC/wFLAtYCIgPLAmYBjf+G/mD+fP6z/lj/mQALAvICxgL7AWABzwD6/9n+VP09/Dv80/zY/Q7/z//h/3r/cf4W/Yz8qfy4/I/87/tc+0L7lPtu/Gz9IP5L/u39eP0c/f/8Ev0a/Sn9Uf2L/dL9Jv5t/qj+Kf+r/6z/v/8mAC4A9P/U/4//Xf+F/6//uf+6/7X/CwCyACABMgEGAbEA5v/Z/hD+VP27/Nb8g/0d/sv+xf98AKYAaAASAL//N//6/kT/UP/D/hv+3v05/jb/ZgCDAbYChgPmAywE1wPgAhcCeQGKALf/if9NADgCCQRRBFMDPgIWAoACcwKfAUUAEP+n/hn/xf/I/3X/ef9c/8z+TP6b/vz/nwFBAhEBEP/W/Wn9mf0e/vb9sP2a/gAA+QCHAaYBVwF/AEP/uv6c/8kAkwEiApcBdQALAEUAgQGaA/cEnAQxA+YBBAGEAHcAzQDpACUAPv8G/3D/aQB8AawB1QC4/5b+WP6Y/wIBDgJoAbX+ZP1d/XP9bv/gAAgAUQBPAbMAUQCuAMUA0QDx/6f+Fv/CAMABJwLnAlUD5QLRAYcANgCdAQwDmQK6AbEBVAGGAAQA8//mACYC6wCs/p//LgJdA34CD/+I/EL+7ABbAUwBPwEPACL/Of/G/20AOwCK/uv8FP1p/RX+gQBuAVr/5P1s/sv+Sv/VAP4ACQD1//X+uf2V/gUAAAIAA8P/DP00/ln/6AB8A0wDygBO/p/8DP4UAcsAGf6x/Fb8dvss/O8AKAQRAb78Cvxj/zQD1wFB/eD7Uv2J/bj7+vmo+h39YP8zAZYByP9W/0QDnwcjB/IBtPuk+Ob5Tv2XAAgByP6B/af+9wFbBI8D8gNPBaoCdv7X/Fz9Xf40/iX9xPuL+in9zwGUAvEBRgFw/34AYQKAANv9rPxt/Cn8sfrK+2gApAGRAG0BVgEwARkCuwHcAfAB6f+6/jH/r/9C/3P+0P+OAaUB3gHqAIT/MgG8AxIEWwEn/bD7Tv0yABcBTf1++0wA1QTCBKUCTAAe/6H/mP9s/j39L/2K/q7+Nv64/rX9F/7jAloFjQKSAMEAfwDEAcMD0wFS/fn7Lf9qAoIDLQMPASUBMwQABCwAa/y/+zgADgT3/0n6xvvBADcDmQJiAaAAr/8QAAsB3ACpAPz+V/yb/f7/Av8i/4cAMP90/+ACAQN+AC8BSAIJALL+QgCyAW4BHf7K+t/9BgN2A8QB4ABkAJgBCASfA7QAFP4X/fr9awBvAsX+ovn0+8oCiQa9Avj8Nf7+AfICGwKH/1/+D/+U/fT7EP0wAB8DRgGn/SYALAOBAjMDXgFv/sIANQAX+578xAIcA9r/nv6v/T/+UwJrA+4B9wVmB73+dvpB/w3/wPsW/iP/f/yE/If/YAEcAtwFcAlxBMb6U/qvALgAWf1j+3L5W/1lBMUCkP0GALcFQAfoAx3+u/3qAEH9qvkM/gcAj/sn+TH8UQIuBYwBff+5AbcCQwMsAAP7aQDDBCz83PdW/Pf+Yv7E/v8EQQo8BZX9qPtzABEGPAQ4AHH+X/p89/L7AwGXAEUCyQVIAqP/AQe2B0L5PfWmAn0H8P6Z9/73gf8oA9n+Z/23ACEDQwNsAL7+lgEUAYj9YP0L/UH91v+MAKX/lf/NAIoCMgJ5AyAIiwKD9+v7IgQ0AeL/6QFxAJz/df7J/m4DCQTk/4z/yAKwAib/kP3v/af8uP5/BNkA8vn3/aYAgf4TA/4DQvz0+VP9uf9fA+YFpP+594r7AARCBY4DTQKx/5T+qv9aAP/+Zv5zAg0Cg/u3/d4CbwA4AHwDaATuA6X/h/rI/tQCB/zq+wwEIQGC+pr+PgNF/579JgITAl3+bPyA+eD70gSbBCn73/jV/80EIQXgAor8RPlz/4gGtAQa/fr4F/zGA5AFxP51/dQCugNU/2L8wQDwA1X/If+GAQ/+n/6dATn/SACQATH9VwFoCPgCm/2D/Uf8bv7Y/x/+dQBc/wH7hQBMAqH5lv/5C/ADjfkH/ioBfv0T/VkAvABc/1AAwwBXAPr++v2oB9kOcAB/9XL+NwQIAVf/l/74/mH+k/2iAw4HmP5F91H9NwnqC9EDOfmq9Zf8WQOzAiP+5Pql/Oj/sAGOAhMBJgEEATP89v7nBhgDDPxg/JH+tgPlBiP+8/ao/h8J5gf8ADX+0vtW/mIHXgKu9S/7cQXvBPcBzPu++A0BLwboAvj91/n2+1EBjAU7BwwADPdm92UA+gkQBWD0UfUPB8wGg/sB/hECDwOOCF8GRflp9tcDtwnjACj9dv6j+hz8EweFC3UANvZQ/EAGsgaCAFT4FPkSBKkDlfdS9eb8QATeBnn+ufXi/ygLCwPK+9f/of2P+HYBNAfC+2H49QCH/839BgZeBmABNgPSAMz7OwO/C7MD3Pf++A8AJAS9Ahj77/njA60H8f/1+Cz8igXrBur/QvxG+2X6Tf/tA2EAov9oAX/5JPaWADwGFAXkBKX9vvQT+egClQehBor8GvSd+XgCygf4Ben9AwB0B1gDy/3a/23/sv3MAvUEyf0p+1f+wfwjAr0NKgRu9kgAtAT+/yIIBQIJ7hX1jAfzBgYBtf3d+9kAYgVpBG0AUPsD/NgC0QLI+2f6If19AWkHsAGO+EYA+ANk/ckItw4B997xFgY4A9r97gee/E7xIwQqDs7/EPkl/pEAdgM7AxX83/gF/pwFJwKV9037eAOI//v+wwVeABj56ANCCZ/9mvq/ACL9cPc6AaEIOf0l+LMFTQ3nAZ34bPxVAsEGBQIX90j7pQRO/6r7qQK0AYP8GQHgAQsC/AsyBKPvgvalCjIK8P4395n06v7IC9UHkfwS+OD5LgHlBFYAk//8AUf9Cfna/3wIpgUZ+zj4tv+vBRcDDfrV+ioHEATn+WgCRQU2+Wb/CAv//jH60QdD/1/xDwQuEXMC/fp5+sX3Uwb9EP8AIfriASL6MvkeCy0Ik/q2/j/7vfXHBNAKIP2j9+gAgwU5AXIAyPvN80j9AQzrAxX3ovxz/df87wz3B6zxq/mrBXL/MANOBL76Iv+eAkj6HwASC6ECPPvyAT8DmfxV+8kDYgokAaT0TfpcBvcGRwJX+D7z7AMyD1gAhPFS9Zf/2gSYB+wBmvLB8rYG3w1CADX36vq4AGkHfAo7/4/y0PZXAyMJqQet//rxdPVdDUYPf/7p/skBTf1PALwCqf/g/u3/4QJyArT8p/+nBtUA6PymBbcDqfhf+58A7P29ANgC3vqK+r4DXgS7ACAAM/7CADAEBf+v/JD/2P7V/Pf7XgB8BKH+8P8vCVv/VPVmBN4MjANs/fD3MflSBeQGNAD3/Vz55foeCiQKPfnQ+nUEQAFsAiYFbPcM7tAAZREqAaDwlvq1BegH4Qfv+z70A/+kAzIC8gZTAOnyb/jrBncI0v88/Hb/+fwB/9UIFwMS+nr/3gAg/SsBoQML/8P+nwTkAsT5AvpnAKMB3QPeBTb9j/XP/vUGXP4y/UUIXwF/8ej2ogfVD5AJm/Vv7cAByREzCEX6NPfg/KAESwWY+8D2aQOiDHMBb/mc/tH8lQArDZABCfOV/voCXv2tBdkDP/n2/7QA6PvHBk8DxPGL+5INeQcu/GT3cPWA/1EOtge985/zoQCIBCUHxAZ4+N31fwPZAlICgQh3+Cnu1wj2FN37FvRLAqUCfv/4A1sDjv/2/ab9iAIpBZX8pPjaA4gJFQOh/Rb2TPk2DSkMNfYl9a4CVAPzAaECQf2J/Z8AJfwd+sMCEgoVAbb2aPrt/tkCAQqqBAn3evhmA6gDsv4PAfIEVQFZ98T1jALHCFcELAZlA731t/qICvQDQP4WBoz8R/IAAWwJdP/u/SMCIf5s/SQBZ//m/70EUwPc/Wr9TACR/939yv21/Nj/AgVjAxL+dvtZ/5kE+wKTAH7/ffvH/hwFHP/w+f37f/2sBXcJIvs79bMDMwvVBOb6kPWx/+sHCf69+QQBWADKABIF5fq79t4GMAyGAzj9VvW99voGfQ2xAj/4nPeI+9X/OQbtCYoDdfrj9yH4GADLDZgI3fQX85UAnAEvADcLaQgu9t30pwIICDwEsf+9+Lb3XgR/Cf/+nfki/NAAiAYQAx/51fstCaMJWP6d+SL9QAR+B0QBhPkr/JkE5wSLAokBtvye/TgDugICAEf+6P1s/gD+5gFABTH6Q/NTBb8OZf089tf9Wv4vACgDRgEEA/f7dPEiAGsNgf5v+UcF5v2J+BML4AoI9zz5twSMBPMB6PzK+Sf/mQGDAo4I9AT3+xf9//pc/GQLUgmb+IX4I/+j/bH/SQahAb72J/wwCv8EAvZR+NUBygLCA9gBsPlv+KH+xgjTDD78ru1++bgJvgfa/6n8Y/r2+lf+7gGdBh4Hi/1w+IcBOQOp/LEDjQog/273hwHkBDr8nAEaCvL8YfbcBpwIFvvpAPMEU/ZE+EUHxATF+iL9OgI7/VP6Vf8aAo8DYwcCAwP2rPXeAXYEVQCDBQ8Hy/Rc65wBtBHvBkz+Jfpp968E4AywAuf9sP4f+yP9hADRApwLvAea9pLzov6/C4gQ4QCf7XHzxQdtDlsDu/gC+Q/6+v09CjEJkfeQ9WMFoQfm+rT6RgTV/rz51QZDCHD3q/V4AicJ5wbS+3D0SvyRBUIGdABd+5T9oP+J/TcBZwhFBoP94vck/iEKdwUX+uj8rgCf/AL89wNKDNwG3PVz8vEC5Ql+AtgDjQKy9Qz4YwjKB6v5/vr3Amf+xPlZ+rz/0QnmCXf8Y/NE+b8BrQRtCEsGjfnS9gf/jP9uAzwKSvv/8YsHBw37+dP2gP/kBoYKDwEL9hD4OABGCF0Jffzg8qP4GQF4CBAKu/4L+soCMf+59QoAeQzOAmrz8fe8AlT9DvxnDJYMN/Sh794FhwtH/zgBswSc+3j9hQPn+836CgTaBOYB2ADi/bz9xgAjCEEM/v7M8yv6egHdA2AEogFJ/UX4mvlwBVwL5wNd/bH5evch/r4FHQTn/Iv4Kvph+wn9xQP7BqADIgEq/JL4mQJZDJAK5AA073rwBg0AEzr+J/xu/w33bQLSEGcCUPY8/X3/2AAsCj0Ft/PZ9d4G8wLF9XwA5wmo/DP59gOFAJ37GwdiCQr49fE9/mQCrAGGB+YCNfhU+6QDkwPe/uX8w//wBdcHy/5m9Pj00P7hCx8PUf8/9PL8tQHvAsEN1Qdm8vfzOgPNA/j9GAFNByoCBPTt9K8L/BGO/D71XADnAKP8jgD1AND8nQAoBfAASP0m/XD6Cv0RCroNqv1A8IH23wYbDE4BfvqC/HD7OP32BSsFcfnt+h0JkwZx+EX6aAPJBLsEIgGn96j6KwqzB7L3AfpsBQgEegBZAgr7+PWVB6MOUfv09mIBGf6g/28MWwN68iD57f6O/aoKWA7S+IftkvrBCGUKSAGm9ln4jgODAxn6evw2BbQAqPcn/7MJFQFa+3EIfAjl9qX2JQPeBNUF6AZR967sPf/5ESAKAPpM+4gCe//MBDUQ8wVu8ZfxK/1AAMMEjwfv/eX2jvep/EsL+g8V/GLy0gEhBw35T/biApMFgQDT/Fz6LQBeBsECZ/sR/pgHQgOP+iEAugRD/D74XAHbBqoDpP+w/CUB5we+ASr6Q//BBs8H9gC89WH1KwPxCGoANv7nAKT7XvqmAQMGEAS4/ab4Zf6tCLb+vO4Y/NoKKACP/agJcgFe7pL4HRFsDwv9RPZy+fD8YAHlAwcCKf50/BoAOAB//G4CGQ2aCWT5tPLC9nn+6Aw2D2j+xPLb9EUAGAtdCb0A1/d992wGhgyY+KTsPgUzF+YB1O6b9HEBQAukCWsAXfwM+bn3NwUUEc0BH/HG/C0Guv0U/2oHigI5+0kBKgZsADL9uP7nAIP+dvrSAasFPvmt+q8ORgpS8+32TgXPAYb/cwGA+Yj4JwMsAyj9ev8sAY/8OfnR/YYKcw/t/xrxB/hiBO0GTQfSAu/3evYrAUoHJgKzAXcIMwPV9nb4fARaCXEDz/3v/Sj+BP/PAWAA3P3k/pP93v6FCUEHUfGO8XMJqwno/HwA8v1R88787wiJ/pX34APTBwj7tfevAYYDvAA5BzcIGPwI+B/7/PnVAs0OLQaW92L6JgIYAV0CdQf4BAD+tfm3+kkEIwmb/WD2hf9OBQkBDwBY/ln5ngCuCKr/Bfe3+/YBiAOPBEH+N/Jr9wIJZgtvA/UCo/5R7kbwuQoqFtMIwPg082j3TAA3CjMOeQkt/EXv5vTKB/oPRQbV+hD7v/5h/9QAxv8S/QEBgQZkAur3XvXQ/goGuwMIAqgCKfsA9AH+9wmjBWz8oPor/RwAyQSQA5v55Pn6BrgJNfzT99cFMQjd+k75hwMKCJkCv/0G/vT93v0iAI0EbwVh/3z8lwGeA0H9nfnF/bwB5wNrATn6C/thASYDmwFN+kf1owKZDQsBZPi3/Fr7ogGdCvj8nfOtAYcH2PwD+9sEDQiiATf+DASlA833HvqICaAGqPcE+kQEfQMDA70Eufom9WEIuBRL/u3rj/syDFwGJP2g+9r3E/a/BeATPADc6o/+/g9f/yD5YwTL/y34OgFcBSL9Avvj/gsD7gUgAEb4kP6pCcQD/vkN/Sf+lf8nBrABrvrk/Aj+Cf+9BX8Guvz2+mID4gTHABr9YPuz/jkE0wiUBEf2QvPQ/18HHwl1BkP5efVsAOj/z/tBCgoNP/PW7BUG0RDYAaf4fP05/ZD7rgJDBL/+2gNjC8H8uuve+SAN0wlXBLsAjvIz8VYJVhIm/iT0bv+zBv4BxP5+AV7/uPjg/j4Ogwik8U3wyAK0CzgL8AWh9TLrnPrkD50MJPlC8ov8ZQNuARsG9AeL+Tv0+gPxCuz/evx/AO36GviXASkI9wV0AvH6SPLc/IcOIAi7/soEs/yN7xEAyQ99A37+/AF388Hztg9lD+fzOfZ4Ca8FhvuM/oAAuP1yAMb/A/sPANkEWAIE/974gfloBcAGnfpr+pgBlgCFBYUG9/ZL9GADhwhkA2cEvwIP92j3KAWlCbAEWwCI+sX2ugEHDSsFg/kr+Wr+CAImB0gJY/yU74L3bwg8CgUBk/yU9/n3swMhCLgExQLg++byJ/g3CG8MtQCU9dD3UAD8BUcGbvtu+scJDAS89DUALQsAAKT/mwjB/Ur0tPm4AcsMLwtS/f320faxAAcP0wiG+OD7XQEw+eH95QeQA3kB8/9k9VbzhAOlEdAJwfYX8AX7xQYpCWcF/Ptr9kP6m/2rAlYKGAZP9xXyrv6qC+MGivzy/+sGJgD79Ln3kARtCnMEnPtx+gb/wv2L/aYJ/wxk/Xj66AXo/gL0Vf58BHz+dwRKCFn5h/QrAbgFiQZhCML8EPPe+SABCwZvCuL/I/Ej9x0EGwWXAxoD1/qE9MIBOw2D/hr1OAJWA5j4wgDVCW/9MPhgAL0AzwV9CVn65ve0BI0A4fzVB/MDYfcrACQG6Peb+GcKCgzM/X/48fzu+9kBygwPAYD0Cf8JBkMEeAVH+2XyMASNDYn6NPYoArcBeQAFA4b9CPjN+rgAUAjTCCL5zPGH/ggGhQZaB637s/E9AGALwACU/SYCgP7BALwFV/2L9yMBgAcnAxAB9QD9/U/9RQFEBPX/nfo1/60FdwLfADECVPax8F4F6xE7ArH3Uf5e+0r2fQmGE8P6XO7K/CoCGQHyBq0EOPrE9ZH6Wgk2EBL+k/OnAeIDEPuYAoAIqf6p+pH+hv4sAXYCQP15AHYI6AWt/df5y/7EBYT/afZ0AeMMoAOz+kf18/GzBXYXPQRw7jD3wwMRA/cDZgNR+2H3kfzmAuoCIwLxA9H9O/b//rkJYgGO+IQBigdp//D7xf4E/dP9cQKBA48EUAIe+Q/5OgZyCOn+MQGIAib3mvi6BoILKwbC+mHxCvs2DKwICv5y/pL88PubAmwByvt4AfgFO/tq900DegcxAlAAIv+x+8r7Uv3X/LEDZguXA0f4FPdd++kE3AvCAgT4rfyFAYH9PP9OAzAAGgIiBgb8CfWlAWcIz/1l/B8JgQft81HxjwUMDGP/+vmP/poBqgGNALf+YAEvBu//g/b2+XQD5wZTA+P+cfu0+Q//OQjfCm0Bhfcl+9QAPAJrBu0CuPVN9nMFBwdc/7kDsgJc9FP0WAT/DGMINfwo8rP3hwcYDIwBPvjP+KX9cgIWBt8EgP7F+w3/PP3b/FYJCA0O+5Twbf6VCSUE1gBQAmr+b/gH+6IHVA0TAuP2ZvwtBSQBYABxBwn/Y/In/GIIRAKq/Hz/2P9JApYGBwDz8kDxLALAExQMfPYD8hP4n/sdCqgUMf/U60X8LApnAPv+jwUZ/m/6yQI0AMH+bgl+AtPzhv+9C+T+k/qqBg8C5fbM++UCZARqBFsABv1q/yQAvfxS+/P+YwZdCF37fO8j+hsK6AaY/K7+FQIq+Dj2pAofEtr6we1c/NUGEgWKBsICK/WZ9n4G1weL/roASgX3+YD2wQrVDRr58PdoA3b7G/hAC5cMVfej8qr7nwNBDX8IRfSa8nQDJgVB/akBDQPq+n/8uwIqAjYBMP+n+eT82geJBD76Pv8BBE77yvoJB/wHTv63/E/+z/0tA+8GUgLn/jf8ufqIBIYL6QDa+Fj+lwD8/9wEuwEV+o/+LANq/4L9ZP54ABMHjwas9Xnw1ALrCbMBnwRRBefxcez6BrEVtQbZ+O32m/jc/f8E8QfHBSL+t/bi+O/97gLTC2wMjv7J8uvzxvubCPUSpQhJ8wfvvf0UCi0I4gKP/0D4XfrnCGQFRPED+bQUVQwO7+vxpQNIBaUEwQaA/7/2o/kZAy0IaQJ8+IL9qgch/+T2nwDjB6cD1/8c/if9nwFoAq39MAHtAvn8d/+fATz6IwCfDnkE2/JS+ckCTQHxA3kEiPwD+f76eP9fB+sFIvq398v89/9ACCQLzPwT8+P7FgVLBkwFgf6m9z38MQSRAzn/BQJxB48BIvXg97kI8wvB/tv6nwAa/zH9FAJzA+f/+vxX/LkC5gcX/Enz8AL3Cqn77/gyBB4A6/h2AHMCNPqF/isIOAEq9+j7pwEiAZ8FkgeC/TH5df9b/cn8bgmPCAv5nvoXBhECKfxyAlMEZP85ABgC5QCv/3/7jvouAyMIsQJN//T9F/Zq+LoJGwx7/Oz0gfnZ/84HLwpb+u3tmvxPDMcG+QAJBEn6puvw+bcSdg9l/q34Tfj29/kBEA4GDN0CGviK8O/6UQ0TDDj+dP3LAA/7Y/wCBbUCAv0HATYEN/+A+hP7Ef67AWwFagWd/n31TfczA3cHnwPk/0b6GfiNAbsJ/v8g9e796QiuA1n7MwA/Bif9pvUC/yEK6Afm/0b+g/2X+gD9UgScCGUDcfso/GkBwAKZAKP+lv5PARcCzPuO+7UEqgSz/TD7tvlU/QkIuQcd/Oz6W/34+ioEeAqm+zD01gAUBCT6GwBPDdAEt/Ue+1sIrgMT+o0AogUz+5H3vARuCeAANf8G/hf2jf8PFFkJuO0m8zULrAoq/Qj+M/8M9dj5jhAHDtXxd/M9DKAE7POkAioLKfq+92sE4QB9+xwCWALq/qP/RP3n/jYHHAU7+m36m//N/7gE4gRI+wD7xv+Q/gYCcQeP/4b4igKMCP7//vnx+6n/AwLwBh4J9fyr8lT7zwSNBMoIkgf09gbzCv92AboDXw2eApDtv/akDOcIlPvZ/uQBNvn4+loFFAKm/nQJLAfy8KTu0AWyDxgGDv399134UAHNB9MCBv3A/qcB6wDV/T3+RQJ6/yX6LQODDQ0A7+8A+q8I6waZAxEBi/YD9ZEEiAvF/zb3afzCAlwB4v+lAt//h/pu/z0GsAFe/NT+Cv7B+88BGQZGASr/VABj+j74gAPwCWsEfwHy/O7ytPlVDHAKAf1c/bX+j/lC/5MGiv5C/CYHfwS0+df80ADM+xAAgAmHAD/2WQA3CDEAB/q9/sMCTwCp/lj/e/84AMoDGAPy+xn8VQE/AeIBmgPyAJn+Pf23+vv/tAoTB1z50vfJAPgE2ABo/ssBKQKd/nT+nAJCAgD8GvtUALID/gJhAFv8Yvpq/3MF+QQV/wf8eP9S/2f7SQAdCCsDPvlU+vEBVgT1/h/+OAfCA5z0H/p7C0kHV/qT/UAChv4Y/7AB6gFJA+cBt/uj+pED6AQI+9j9GAl+Aa3z8f3vC84Bifcs/84E6P6i+lH+/AIGAzz/uvxX/Zf+GAG0BJoEmv7m+OX5YQD1Bt4Gkv4k+In7OwL5A8sD6QMQ/wT7lf+7Af37c/5RCmcHU/eh9c///wPSBVsGKf8f+X78DQIuA1EA3vtH/VwEjAKo+sn7ogBxAfkDNgW9/YP53v0k/7wAUwSCAIT9BwBG+1b50gcMDSz+5/Yw/Lv/JgJZA1AAnv7Q/hX+rACoAzoA/Pp/+7ICKgjGAm76PPsYAUQDxQEVAFv/3f8u/yP+kwAZAjUBigI8Auv73PiDAQEJLgIf+5j/UAGq/KT/gATm/5f8PwD/AT4BTP5i+sH/YgehAa75oPwOAXABqAGI/+r7gf18A7EEKv5C+gT+ZgJhBJYDiP46/JEAWABN/RMC1wOg/mj/cgJZ/h38qQG+BBICD/+e/Ar9tAE+A2z/gP0T/9MA5QEuAUP9TvuO/60CuwDU/n3+yv4ZAQMDCv7T+K7/WAddAsX8UgCIAQ77g/uQBLkGfwD7+3/+KwKhACH/2QKWBcj/8vls/rwECgO0/v3+KgBk/88AWwKj/2j92//eAW0Adf5K/dn+ZwINAnz+TP48/1D98/4KBC8D0P1s/HD/nwEJAdH+9f1pAU4EDgGN/EH+JQO0AUX9yv4bAycErADD/Oj98gEPAtT+Rf+lAcUA9f8SAAb/Lf96ABsAm/+wAOf+k/wWAOUCfwBZ/fn7bv6pAhYCmf4R/6T/C/6BAIgBJv2H/WUCSQL7/bf9wgH2AX3+Tv82A9YBd/7N/xgBkP89/iv/TwITA7j/Z/5BAMcAHAHhAIf+Sf9EAnIBqf8s/+n94v2bAGQDMAJ0/Hf7UwIrAwH+bv95AVH+Nf/cAqv/qvvu/kcCLQE+AN//vv6U/3sBFAAh/1ABVgAk/rv/IQF+AET/iP78/4EBRABD/9EAOgHA/0T/Tf8hAB8BBwHpAOb+zPx1/zQCsACUAHkBof7B/S4A5v9a/xoBsAAm/h7+kACGAUr/s/5rATEAr/zu/kUCZgHnABIBZP6H/E7/sQJXAmz/OP6kAH8C5gCf/qv+8wBkAiQBaf9o/yMA2P9e/+sA1AILAbz90f36/1wBPgKqAYf+YfxU/mABcAFg/6D+Y/9w/3f/qgCeAA3/4/7l/zsASwBaAG//jf5N/wMBDQIhASb/iP6m/z8BUgIbAowAyP6G/ksAEALzAeAA1f/0/mH/PAH5ASQA4f4oAAMBQQA2/6D+L/9ZAKUAv/80/63/Xv/D/oT/TADR/zH/O//a/p3+yP8XAQUBT/8I/jP/ugCkAEQATwAeANj/AQCEAEQBjQEtALj+gP9CAWIBUQAwAKIAIAB9/38AYAEaAOn+J/9z/6v/lwCJANH+bf68/z4Ah//2/in/Yv+N/wwAPABq/1P+n/4bABABnACK/2j/y//r/3oANQEAAUUAawCqAP//GwABASsBlADI/zAACQG5AKwAGQFbAHv/QgCpAM7/BwBbAIf/Of/W/1gAGQCX/4P/mf+2/+T/DwDt/7r/yv97/0f/v/8bAEwAIQCB/3z/4f/3/zcAtwDBAHEAJQCD/wz/nv+NAO4AewCi/1v/jf+u/14ApwFqAaD/Hv+p/3v/hv9kAJMAwf83/07/uf9GAIMAZwBlAEAAqv9s/9H/KAAIANH/xP+y/9L/DAAZACEAQwAfAJ7/ov/f/7v/8P8+ALb/GP+D/x0AAAAPAEMAy/9s/6X/SAAuAd4AV/8F/wIASgAOAI8AqQDX/7L/TQCOAF8AWgBRAN3/6v9sAD4AGQDLABoBXQDe/woAx/9U/8//hQBZAAEAMwC9/8D+Rv9hACAAZf9S/1b/Ev96/0cAMACJ/zz/cf+n/6H//P+oAKsA5f+P/xAAYQBQACsA7v/p/0IAsgDPAHEAAgA2ANAAxQAqAAAAXQBeANn/hP+m/+r////b/8H/BwBTAPb/dv+9//P/k/+J/5P/a/+y//n/qf9n/8D/aQCqAB8Ayv9BAIIAQQA2AE4AHgDt/x0AWQAXAN3/QwC4AMIArgCQAFUARgBHAPX/b/9F/+n/hgBRAOr/WP8P/xkADgFaAAv/uf5g/x4AIQBG/83+RP/1/4QAiQDc/1H/lf8xAEMA+f8dAF8ASAAtAC4ANgAEAMD/CAB/AIcAdQBoAC8AAgAnAC8A1P/d/ysACAC4/83/aACHAJ7/Hf+6/0UAHgDw/7D/Ff8q/83/EQA+AB8Aev9G/xYAwACCACYA5v+K/2X/sP/8//3/CwBwAMgAjQAbAAEAUgB9AEcAHQAJANP/iv+n/wMAHQBGAFAA7v/e/zAAOQD9/7T/pP+s/zr///6k/+v/of+7/+T/DQBhAF4AEQAHAAQArf90/3P/sv8zAGQATgA3AAkADwCXAFABOAFZAL//j//U/28ArwBSAOH/6f8VADMAYQBHABcAHwAcAA8A/P+4/4j/sv/g/8P/mv+H/5j/2f8VACEALgBgADwArf92/xAAkAADAGD/sv9mAIMAQgBdAHYANQAYAEEAUwBMACsA6v8AAEsARgAzABQA1v8PAH8ATQDS/7T/sv+W/6v/0P+G/wT/Lv8KAHIA4/9J/zz/k/8YACsAnf8b/zz/3v86AAsA1/8oAHMALQATAE0AYABqAIMAaQAIAN7/OgCyALsAZAAOAO7/LACTANAA3gCTALX/Ev+I/ywADAC+/6r/jf+h/+X/7v/X/8f/4/8eANv/R/8R/y//tf96AGYAlv9p//T/ewDSAL8AHwDp/2IAVwDu//j/QgCgANMAjwA1ACAAOwCVAOgAtAA9ANj/uf8KADAA4f+n/43/ff/D/ykASwAfAMX/pv/G/8j/hf8K/wf/zP8PAIX/fP/D/53/zv+QALAADQDM/xUAPQAhABYAFgD3/x4AkQCiAGwAkADlAMsAZgD7/57/+v+SAHEA/P+C/0v/y/9rAFEA9v/M/17/Vv8RAEUA6v/K/5P/9f7O/qD/LgA1AD8A6f+//xUA7f+B/9//ZwBUAAoAzf+z/wkAowC4AFEA8f/I/zQArACBAD4AIgABACYARAAHAOj/7v/K/6b/sP/b/zUAdwAWAIH/qv/9/9j/0f/d/5f/af/6/3sA4f8//47/JgBhADoA6f+m/8X/TwDMAJsA5P+U/6P/3f9mAGQAEABoAHQAyP/U/4wArgBJANn/c/+H/wcANgDj/2D/LP+p/10AcQDN/zb/PP+s/ywAegAiAF7/Yf/1/wIA6/8EALz/Y//O/4UArQBxAAoAw/8hAKgAsABXAMT/Wf+k/2YAzQCPAC4ACgAfAD8ASgBiACwAqv+B/4H/qP8UAAMAgP9f/63/BgBJAEAA1/+C/7D/CgANAOP/r/+S/9f/TAByACYACQA3AD0AgQDqANQAWQDT/6X/KADOAKgAGQD5/xYAIABvAL8AjQA0ANv/l/+q/8r/v//W/9P/Z/9h/8b/rP+k//T/4P+s/4z/Rf9C/8j/JgDK/1z/Wv+M/+7/VwB4ADYA9f9OAPYA0wDx/7z/cQDiAIIAAgAXAHoApgC3ANMAngAnABMAYwBeAOD/iP+1/zcAbgAEAHH/F/9A//n/QADb/4r/R/8w/5n/qf8o/0//9//e/3b/if/D/wQALwD2/8X/9v8oADcAPAAVACIAgQCQAFoAZQCkAJUARACAAAEBpgDg/7f/2P/+/4QAwgAzAKn/l//5/24ANgCu/2//YP9N/z//lf/4/7X/O/9k/7X/af9y//z/1P9//9L/7f9u/13/5v8ZANH/xf8gAGQAbgCAAMIAwwBaABwADwD6/xcAgQDOAIYA/P8BAI4A1wC6AD0AkP/G/3cAKQCW/4j/f//N/2oAOABk/yv/nf8ZAFYACQBg/zf/nP+1/4D/eP9+/6D/3v/R/9z/IgAlABcAFwD1/+P//f8dACgAHAAAABgATgAtAD8AyQDHADUAGQBpAHIAWABNAPf/sf8KAHoAcwA9AA0A5v8GAF0AVwACANf/xP/P//7/5P+Q/5X/4P/9/9L/vf/s/w8ADQACAPX/1P/H////JgAKAOz//f8xAEgAPQA2ACUAEwAaAEUAhACJACoA0f/c/yYAcgB3ACAAt/+W////cQA5AMf/1P8tABQAo/+w/wsA9f+f/5P/uf/M/8//tv/H/wcA5P+i/8L/AQACANb/3v8VAPj/tP/s/0YAMwAKADcAXgATAOz/UwBnAOn/2v9aAH0ANwAiAAYAyv/3/1sAWgADAMj/w//i/xQAIADr/5T/cf+5/w0AEgDp/8P/u//O/+D/4f/3/wwA8v/Y/9P///9dAIUAUgDz/6z/2P9NAJEAgQBIACQAHAAcABIABAAdAFMAWQAjABoAMAARAO3/9P/z//b/GQDs/53/xf/5/+z//v8IALz/iv+7/+v/1v+4/9b/+v/H/6n/3//2/wMAIAD9/9P/7P8SACAAGwACAP3/KwBZAHUAewBAAO7/+v9CAC4AAQAhAC0AIQArACYADAD7/wgAIgAtACAA/P/T/8X/2v8CABEA3/+n/7b/7v8OACMAJAD4/9f/yf+//8f/8P8gAAgAxP/J/xUAJAALADQASAAhABcAFgDw/9H/DABsAFEA1P+i//T/TQBLACMAIQAiAAEADAA5ADAAHgANAPX/BwAIAPf/CAARACoAWQBBAAoAAQD8//X/EgAPAM3/uf/g//f/DQALANj/uP/g/xAA/f/O/9f/DAD7/8r/xv/I/87/1f/B/7z/5v/7/9//5/8aABkA7P/+/w4Az/+8//T/FQA0AGoANwC//9j/ZACbAE0A8v/i//f/FAA2ADYA8//J/xQAXAAlANT/xP/u/ygAJwD1/9P/x//N/9r/3f/6/yoAHADS/63/0v8AABUAMQBWADkA3P+5//T/NgA+AD8ATwBHADsAKgAKAPv/JABZAEgABADt/yAAPgAiAP7/5P/T/+//OgBAAOX/s//O/+v/8//j/9r//v/9/6r/gv+8/wIANQAqANH/qv/J/9H/2P/6/yQARgA0APv/4P/f/+n/FAA5ADcALwAdAPr/AAAcABgABwAKABoAIAAcABYA+v/W/9r/CQAlAA0A4v/W//D/AwACAAAA/v/+/+P/uf/C//H//v/9/w0A/v/r/wUACgDq/+z/DgAXAAkAFAAgABAACQASABcADAABABYAGwD9//n/FQAnACsAIQAPABYAEgDh/9z/EAAUAP//BQD+//f/AAD1/+L/3f/l//j//P/3/wQABgDt/9//2//S/9//+P8BAP7/+//+/wIADQASAPr/8P8BAAQA///8//X///8YAB0AEAAIAP3/+f8DAA0AGQAdAAoA/P8JAA8A/v/v//D///8RABkAFAAHAPT/5P/a/+P///8CAOr/5f/7/woA+//i/93/7f8AAA8AFAD8/+L/4v/i/+P/+v8VAB0AFQAJAP7/7v/m//D/9//r/+n/BAA9AHwAcQD3/3//kv8WAHIATADS/4f/uP8jAHcAbAD7/5v/q//7/xsACQALADEANQDp/7X/zf8RAE4AZQBzAGAAIQCBAJwBuQGU/4r8SvsC/ewAigTbBA8C4f4g/Sz9nP7eAAMDlQMaApL/Hv3Y+8n8ov84AuoCpALFAfH/Hf7z/Mn9FQA3AOv+XP9AAMr/q/+XAe4EHQcoBSH/hviK9c344wDtB8oIwQMP/cj4jPh7/K4CfQaqBRwCGP7a+zP8z/2L/8UAkgHLAUIB0gCnAGYA4f+y/zwA2f91/h3+Gf+HACgC9AE6/6T97f0g/3AB8wIaApz/p/7N/2P/ef4CAOwApf+MAPQDHQZqBlMDofx593L2jvnsAAoI/AgIBPH8ZfYY9TP8lAWoCYcISwRn/f/3hfjE/CEBIwTFA20AXv3z+4r9yQHsAgUAy/5T/1j+f/5LAW4CygEdAhcBEv7O/YD/uf9tAUkDBQHh/rL/Yf/3/poANgG2ADX/kf26/6gDygNjAN78F/tG/q0DRQS7Ajj/7fll/E0CYANUBOkCvfyI+kD9CP8UAPcA1gE7AtP+pfzt/hX/wP+sAjEAHfwJ/7sCVQCw/osA+/6A/K3+sv/xANkHzggk/zT5svqK/BkASwUlB2ICmvlU+cIA8gGkANkFGAeH/bL46f3kAaED0wJT/h4B2waf/6n5uQIbByr///y5ArABMfv4/A8Cn/6j/NkBNQFV+378fgC4ADQBYf6b+pkAWgTu/gH/vAFu/4L98v2n/zMAhgHQA7D/b/wPAIb/hPy+/jkCIwP3Ag0B/frd+3UF4AYnAiwBMgEJASwBDP7c+8gBlQcgBaD/6/tp/PMAhwLz/8/+R/+/AFgADfsl/NkE4gQy/xv8LvvZ/5YDOgGGAKgATfxG+ZD88AONBib9k/eq/TT/8f5jBHIEkf+P/n7+uv0H/lv9sv66BqoHkPpy9y4DmQUH/cH9EgV0ALT7NQKNAAv6ZP/yA2oBgAAO/wv9ygGZBqb/WfuMBNAFN/w3/bMDmQA5/REBOgLF/gIAbAOd/mP7FwPtBfr/3vwSAJcF/gOd/HL8aAPqAXz7FwDkA/D+/v5vA6AAr/lJ+hP/eQF+AwD/F/dv/ewFXf8Y/EMBJgBx/v8BQQHg/Kf7n/0wAnEBUvyR/qwCZQHT/YX9HwKnAUv+jAIKBE/+n/zf/uUA3wPMBMAAz/xN/a0BKQW1AloBUAMyAYj+ov1X/q4C+QIP/+cBXQQD/2/+EQDr/eUDrgck/Vz5mP+W/t79SgNtA7L/if6I/Rj+uwBV/hz9mgUPB3D8H/ka/df9QP9vAowCkADM/ST8S/63Ar4CDPwv/HADSwIo/kb+1/6L/7D+2v78Aj4D7/1l/XMBrQAF/z0CFgEW+xP9GAP8AV3/AQA4ABMCEQMO/jv7BQDUAxcB3v+aATD+4fysALf/F/+hAfcB6AKgAfr8Mv77Adv+0/w9AGAAagCiAkwBgf9t/9v+Wv/GAE0BSAHE/kT82/5lATMBlwCR/qv+fwK4Ao/+l/5EAkcBxP61//39svvh/0wE4QK0/3L/jv8u/kv/VAHtALMAYADk/c772fyWAeIEwQAJ/Er+YwKjA7oBr/1D/az+3P01AYIC1fzU/skDU/9N/twCuv8e/NL/bgOxA9AAWf4t/9v+u/0HAIECwf8U/u8CVgPM/Rf/sAK7AMIAagBg/FD+1QLwAcb/OP4L/wEDKwIq/vj9Hf+ZAlkGqQCe+Nr63v+vAigGtgIc+677n//aAAgC4gDz/ysCQwB0/Dn9rP4aAZsEJAJC/b/9CP4m/FUA2AUOBFf/MP2Q/o8AtgHPARv+Q/zMAd4D0/0D/UUBRgFsAe8A0vzo/aIClgHz/jv/fwB/Aev/Rv6c/p39O/7GAskExgHD/c375/yLAMQDogL4/qz9XP4E/04AjgJ9Aj3/TP0O/hEAbAG8ACUAkwBQANj+lP5O/0H+rv4aApUCQADjAfABMfuS+jMBfAMoAnsAmf/q/xP/s/4TARUCSQA7/+/+xP+mAMD/MQFxA1gBW/4N/A77i/8LBEYDrAGPAHf/Bf8u/v/+zgGVAsEBGgBG/lr/OgAL/73/TADd/r/+Mf+Q/6wBpQLtAN4A6QGg//n8+/2j/1n/gwAUAjD/EvxW/Bz+/gHMBeoEJAH0/vj9Pv10/vj/av+i/yoAWv5O/qkAmwHDAisEVALs/rL9IP5s/0oCfQMUAIb8mvuZ+3n+xgJxBNcE8QNiAYj+z/wF/jIAqACLANf/dvz6+hz/fwJAA6YDnQEy/4z/Z/+M/uf/JQHRAEb/HPyh+hT9lwA3Aw8FoQQtAq7/Gf6Z/nn/Uf/a/xAA9P5z/uT9if1kAD4DQAOzAr8AfP5I/p/+x/9eAVoA0P39/J799P68AAcCJQM0BP8CKv+1/A39vf47AY0Ba/8C/v39CP9YAFgChgPYAQ8ABv/4/S/+//8SAhACpP8h/iT+fv4xAeQDDwM0ASP/+/wo/Rn/iQAWAe8AQwC7/4X/DQA1AfEB7wH5AID/Kf4M/UL94/5sAAUBRgB7/zkA/ADGAB8BJgLkAS4Asv5N/Z/8+P2K/14ATQFYASMAsf8QAI0AjAGoAbYA9P9g/xf/Zv6h/TX+5P6K/xMBtQFXAUYBLgExAXIAxP6f/pb/6f/G/wf/ef4B/+j/qQDeAMoA/AADAfIAuQAjAIj/k/4b/v7+mf8j/9z+u/9+AUwCdwHIACIACP+//gn/Of+o/6AAPgF4AFj/NP/m/6oACQHDAC8A5f/J/6v/tP9x/w//9P/OADcAGQCBAG8A9ACaARMB0v9j/tT9rv6//7UATgEKAeIAfgA9/zH/TgCXAHUAIwAQ/1j+Qf/IADABagDg/+//2P/Y/83/qv8CAPD/YP86/zD/Pv+U/wIAnQAHAQcBmwDm/7X/qP+R/wkAewB/APb/9f5h/gL/TAAhAXMBYAHNAN7/TP9r/6H/yP+u/3H/k/+8/8D/VAAeASIBnwDE/07/AQCsAM4A3gA3AAv/d/5r/tf+CgBVAZ4BSAHwAEkApv9t/77/MQARAK3/Wf85/4L/4f8tAJkAvgBvADQAFwAFAFwAvgAvACb/vv6x/tL+ff8aAD0AiQDbALQAYwA2AFwAZgDN/3D/rP+n/5b/v/+Y/6X/6/+//xYA9QAnAQIBqgC3/wD/OP/K/+T/kv+M/7r/wv/9/zgAOQBTAGQAagB6AEkAx/9d/27/wP8BAAEAo/+Q//D/FABJAJ8AZgACAPf/wP+f//r/FADp/8v/p//L/wwAIABBAFAAMQAiABEABgAyAEQA7/+r/77/zP/h/yUAZABeABsA2P/J/+j/7P8HACkACQDs/+j/4//X//j/JAAWABkAGgAIAP7/y/+w/9j/6v/i/+r//v8NAAMA+f8cAB0ABwAxABUAsf+n/+b/JwAuAAQA9f/q/+//EQAbABoAFAAOABIAAADv/wUAAgDX/9z/8v/h//P/KwBJACkA3/+5/9r/HgA/ACsA+v/G/8X/5P/0//7//f///wEA7v/7/x8AHgATAA8AAQDz//n/9v/Q/7n/0v/+/yUAKgAUAP3/8/8KAD4AUgAqAPz/yf+h/7n/3//q//T/DwAnAB8AEgAgADQAQgBPACkA7v/j/9b/uf/E/+n/BwAgAB8ACQAIABcAHwAbABMAGAADAN7/3//n/8//0//6//T/9P8WAAcACABCAE4ATQA7ANj/qf/N/8z/zf/6/w8A+f/v//v/CAAlAEAALAAEAPX/9v/w/+T/3//n//D/9f/8/wQACAAMABoAIwAhAAsA5//g/+f/9P/3/9j/0f/l//z/IAAZAO//9P8PABIABwDw/+3//v/+//n/9//z/+n/6/8IAAgA8/8IADgAQgAMAMb/wv/8/w8AAAAIAAYA7v/w/wwACAADAAsA/v/6/woACAD7//P/6P/3/xMA///m//H/CQAVAAIA/f8HAPv/AgAIAPP/7//6////+//8/xUAIAAJAAoAEwDz/+P//P8EAAUAGQAXAPz/7//x//z/CAAGAAsADQABAPj/7f/x/woAFAATAA0A/P/x//z/AgD+/wIA+f/2/wsACwD+/xEAIAAIAOv/5f/s//7/FAAQAAIA+f/j/+f/AwALABQAFAACAP//+P/w//P/9f8JABgACgD3//H/+f8AAAIADQAVAAsAAgADAPf/7v8AAA0ACAADAPj/6v/z/wkADAAHAAYA/f/7/wIAAwAAAAAA//8DAP7/8//8/w4ACQAAAP7/9f/x//r/BgAOABAAEQAEAO//8P/9/////f/+//z/AQACAPj/BgAOAP7//f8DAAIABQABAPX/9v/+////AQD9//r/BAAKAAkACQAIAAcABgAIAAQA+P/2//v/AAACAAIAAwADAAIACQALAAgACAADAPz/+v/6////AwADAAIAAQD8//r/AQAJAAgABAAGAAUAAwAEAAEA/P/9/wEAAQACAAQAAgACAAMAAAAAAAAA/f/7//7/AQADAAQAAAD//////v8BAAQAAQD//wEA/f/3//r//v8BAAMAAwADAAIAAwADAAEAAQABAAIAAgABAAEAAQABAAIAAwACAAAA//8AAAAAAQACAAEAAQABAAIAAgABAAEAAQABAAEAAQAAAAAAAAAAAAEAAQABAAEAAAAAAAEAAQABAAAAAAAAAAAAAAABAAAAAAABAAEAAQAAAAAAAAAAAAAAAQABAAEAAQAAAAAAAAAAAAAAAAAAAAEAAQAAAAEAAQABAAEAAAAAAAEAAAAAAAAAAQAAAAAAAQAAAAAAAQABAAEAAAAAAAEAAAD//wAAAAAAAAAAAAABAAEAAQAAAAAAAQABAAEAAQABAAEAAQABAAEAAAABAAEAAQABAAEAAAAAAAAAAAAAAAAAAgABAAAAAAABAAEAAQABAAEAAQABAAAAAQACAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAEAAQAAAAAAAAABAAEAAQABAAAAAAABAAEAAAAAAAAAAAAAAAEAAQABAAAAAAABAAEAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAQABAAEAAQAAAAAAAQABAAAAAAAAAAEAAQABAAEAAQABAAEAAAAAAAAAAQAAAAAAAQABAAEAAQABAAEAAQABAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAAAAAAAAQABAAEAAQABAAAAAAAAAAAAAQABAAEAAQABAAEAAAAAAAEAAQAAAAEAAgABAAEAAQABAAAAAAABAAEAAQABAAEAAQAAAAEAAQABAAAAAAAAAAAAAQABAAEAAQABAAEAAQABAAEAAAAAAAEAAAAAAAEAAQAAAAAAAAABAAIAAQABAAEAAQAAAAAAAAAAAAEAAQABAAEAAQAAAAAAAAAAAAEAAAAAAAEAAQACAAIAAQABAAEAAQABAAEAAAAAAAAAAQABAAEAAQAAAAEAAQABAAAAAAAAAAAAAAAAAAEAAQABAAEAAQAAAAEAAQABAAAAAAAAAAAAAQABAAAAAQABAAEAAQABAAEAAAAAAAAAAQABAAAAAAABAAEAAQABAAAAAAAAAAAAAQABAAEAAAAAAAEAAQAAAAAAAAABAAEAAQABAAEAAQABAAEAAAAAAAAAAAABAAAAAAABAAEAAQAAAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAAAAQABAAEAAQABAAEAAAAAAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAEAAQABAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAAAAAABAAEAAQABAAEAAAAAAAEAAAAAAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAAAAQABAAAAAQABAAEAAgADAAMAAgABAAEAAQABAAEAAQABAAEAAAABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAEAAQABAAEAAQABAAEAAQAAAAAAAQABAAAAAAAAAAAAAAAAAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAEAAQABAAEAAQAAAAAAAAAAAAEAAQABAAEAAQABAAAAAQABAAEAAQABAAEAAQAAAAEAAQABAAEAAQAAAAAAAAAAAAAAAAABAAAAAAABAAEAAQABAAAAAAABAAEAAQACAAEAAQABAAEAAQAAAAAAAAAAAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAQABAAEAAQAAAAAAAQABAAEAAQABAAEAAQAAAAAAAQABAAEAAQABAAAAAAAAAAAAAAAAAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAABAAEAAAABAAEAAQABAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAEAAQAAAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAAAAAAAAAEAAQAAAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAQABAAEAAAAAAAEAAQABAAEAAQABAAEAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAAABAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAEAAQAAAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAAAAAAAAAAAAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAEAAQABAAEAAQAAAAAAAAAAAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAABAAEAAQABAAAAAAAAAAAAAQAAAAAAAQABAAEAAQABAAEAAQABAAEAAAABAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAQAAAAEAAQAAAAAAAAABAAEAAQAAAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAAAAAAAAQABAAAAAAABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAAAAAAAAAAAAAAAAAEAAQABAAAAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAAAAAAAAAAAAAABAAEAAQABAAAAAQABAAEAAQABAAEAAAAAAAAAAAABAAEAAQABAAAAAAAAAAAAAAAAAAAAAAABAAEAAQABAAEAAgACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAAAAAIABAAEAAMAAwADAAMAAwAEAAMAAgACAAIAAgABAAIAAgACAAIAAgACAAIAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgACAAEAAgACAAIAAQABAAEAAQABAAEAAQABAAEAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAIAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQACAAIAAQABAAAAAQABAAEAAgACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQACAAEAAQABAAEAAQABAAEAAgACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgACAAIAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgACAAEAAQABAAEAAQACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgABAAEAAQABAAEAAQACAAIAAQABAAEAAQABAAEAAQABAAIAAQABAAEAAQABAAEAAQABAAIAAgABAAEAAQABAAEAAQABAAIAAQABAAEAAQABAAEAAQABAAIAAQABAAEAAQABAAEAAQABAAIAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAAAAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQACAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQAAAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAgACAAEAAQABAAEAAQABAAEAAQABAAIAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAgACAAIAAgABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAQABAAEAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAA//////7//v/+//7/\",\"isFinal\":null,\"normalizedAlignment\":null,\"alignment\":null}");

            
            if (writeDebugFile)
            {
                debugStream.Close();
                Debug.Log($"Wrote audio to: {file}");
            }
        }

        private async Task<AudioRequest> SendMessageToWebSocket(AudioRequest request, bool close = false)
        {
            if (!IsConnected) await ConnectToWebSocket();
            if (!IsConnected)
            {
                Debug.LogError("Connection was not established, message not sent.");
                return null;
            }
            activeRequests.Enqueue(request);

            if (!_initialMessageSent)
            {
                var initialMessage = new
                {
                    text = request.message,
                    voice_settings = new { stability = 0.5, similarity_boost = 0.8, use_speaker_boost = false },
                    generation_config = new { chunk_length_schedule = new List<int> { 120, 160, 250, 290 } },
                    xi_api_key = config.apiKey
                };
                await SendData(initialMessage);
                _initialMessageSent = true;
            }
            else
            {
                await SendData(new { text = request.message });
            }

            if (close) await SendCloseTextMessage();
            else
            {
                RunOnMainThread(() =>
                {
                    if (null != enforcedTimeCoroutine)
                    {
                        StopCoroutine(enforcedTimeCoroutine);
                    }

                    StartCoroutine(EnforceSpeechTimeout());
                });
            }
            
            return request;
        }

        private async Task SendCloseTextMessage()
        {
            await SendData(new { text = "" });
        }

        private IEnumerator EnforceSpeechTimeout()
        {
            yield return new WaitForSeconds(timeout);
            _ = SendCloseTextMessage();
            enforcedTimeCoroutine = null;
        }

        private async Task SendData(object messageData)
        {
            string messageJson = JsonConvert.SerializeObject(messageData);
            await ws.SendText(messageJson);
        }

        private Task ProcessMessageQueueAsync()
        {
            if (null != _messageQueueTask && !_messageQueueTask.Task.IsCompleted)
            {
                return _messageQueueTask.Task;
            }
            _messageQueueTask = new TaskCompletionSource<bool>();

            _ = RunOnBackground(async () =>
            {
                isProcessingQueue = true;
                while (messageQueue.Count > 0)
                {
                    var message = messageQueue.Dequeue();
                    await SendMessageToWebSocket(message);
                }
                isProcessingQueue = false;
                _messageQueueTask.SetResult(true);
                _messageQueueTask = null;
            });
            return _messageQueueTask.Task;
        }

        private Task<bool> ConnectToWebSocket()
        {
            if (IsConnected) return Task.FromResult(true);

            if (_connected != null && !_connected.Task.IsCompleted)
            {
                return _connected.Task;
            }

            _connected = new TaskCompletionSource<bool>();

            var headers = new Dictionary<string, string> { { "xi-api-key", config.apiKey } };
            ws = new WebSocket(config.Url, headers);

            ws.OnOpen += OnOpen;
            ws.OnMessage += OnMessage;
            ws.OnError += OnError;
            ws.OnClose += OnClose;

            RunOnBackground(ws.Connect);
            return _connected.Task;
        }

        private void ProcessMessage(string message)
        {
            var data = JsonConvert.DeserializeObject<AudioData>(message);
            if (!string.IsNullOrEmpty(data.Error))
            {
                OnError(data.Message);
                return;
            }
            if (null != data?.Audio)
            {
                var request = activeRequests.Peek();
                request.charsRemaining -= data.Alignment.Chars.Count;
                Debug.Log($"Processing {request.message} leaving {request.charsRemaining} characters to process.");
                // Combine the chars and log it
                Debug.Log("Chunk contains: " + string.Join("", data.Alignment.Chars));
                var events = new List<PlaybackEvent>();
                if (data.Alignment.CharStartTimesMs.First() == 0)
                {
                    events.Add(new PlaybackEvent(0, () => request.onPlaybackStarted?.Invoke(request)));
                }
                
                var startTime = data.Alignment.CharStartTimesMs[0];
                var endTime = data.Alignment.CharStartTimesMs[data.Alignment.CharStartTimesMs.Count - 1] + data.Alignment.CharDurationsMs[data.Alignment.CharDurationsMs.Count - 1];
                var length = endTime - startTime;
                
                for(int i = 0; i < data.Alignment.CharStartTimesMs.Count; i++)
                {
                    events.Add(new PlaybackEvent(length, () => request.onCharacterPlayed?.Invoke(request, i)));
                }
                
                if (request.charsRemaining <= 0)
                {
                    Debug.Log($"Enqueuing completion events at {length}");
                    events.Add(new PlaybackEvent(length, () => request.onPlaybackComplete?.Invoke(request)));
                    events.Add(new PlaybackEvent(length, () => request.onComplete?.Invoke(request)));
                }

                audioPlayer.AddData(data.Audio, 0, data.Audio.Length, events.ToArray());
                if (request.charsRemaining <= 0) activeRequests.Dequeue();

                debugStream?.Write(data?.Audio);
                responseStream?.Write(Encoding.UTF8.GetBytes(message + "\n"));

                RunOnMainThread(audioPlayer.Play);
            }
        }

        private void HandleComplete(AudioRequest request)
        {
            Debug.Log("Audio clip completed: " + request.message);
            if(!request.Task.IsCompleted) request.taskCompletionSource.SetResult(request);
            else Debug.LogError($"HandleComplete was called twice for {request.message}");
            request.onComplete -= HandleComplete;
        }

        private void OnOpen()
        {
            RunOnMainThread(() => StartCoroutine(WaitForConnection()));

            if (writeDebugFile)
            {
                debugStream = new FileStream(Path.Combine(Application.dataPath, "test.pcm"), FileMode.Create);
                responseStream = new FileStream(Path.Combine(Application.dataPath, "response.json"), FileMode.Create);
            }
        }

        private IEnumerator WaitForConnection()
        {
            yield return new WaitUntil(() => ws.State == WebSocketState.Open);
            _connected?.SetResult(true);
        }

        private void OnMessage(byte[] bytes)
        {
            string message = Encoding.UTF8.GetString(bytes);
            ProcessMessage(message);
        }

        private void OnError(string errorMsg)
        {
            if (activeRequests.Count > 0)
            {
                foreach (var request in activeRequests)
                {
                    request.onError?.Invoke(request, errorMsg);
                    request.onComplete?.Invoke(request);
                }
                activeRequests.Clear();
            }

            Debug.LogError(errorMsg);
        }

        private void OnClose(WebSocketCloseCode code)
        {
            if (activeRequests.Count > 0)
            {
                foreach (var request in activeRequests)
                {
                    request.onComplete?.Invoke(request);
                }
                activeRequests.Clear();
            }
            if (null != _connected && !_connected.Task.IsCompleted)
            {
                _connected?.SetResult(false);
            }

            _connected = null;
            _initialMessageSent = false;
            activeRequests.Clear();

            CloseStream(ref debugStream);
            CloseStream(ref responseStream);
        }

        private void CloseStream(ref FileStream stream)
        {
            if (stream == null) return;
            try
            {
                stream.Close();
                stream = null;
            }
            catch (Exception)
            {
                // Ignored
            }
        }
    }

#if UNITY_EDITOR
    [CustomEditor(typeof(ElevenLabsWebsocketStreamer))]
    public class ElevenLabsWebsocketStreamerEditor : Editor
    {
        private string speakMessage = "";
        private string speakQueuedMessage = "";

        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            ElevenLabsWebsocketStreamer myScript = (ElevenLabsWebsocketStreamer)target;

            speakMessage = EditorGUILayout.TextField("Speak Message", speakMessage);
            if (GUILayout.Button("Speak"))
            {
                myScript.Speak(speakMessage);
            }

            speakQueuedMessage = EditorGUILayout.TextField("Speak Queued Message", speakQueuedMessage);
            if (GUILayout.Button("Speak Queued"))
            {
                myScript.SpeakQueued(speakQueuedMessage);
            }

            if (GUILayout.Button("Play Test Message"))
            {
                myScript.PlayTestMessage();
            }
        }
    }
#endif
}
